services:
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Deepgram_stt_google_tts:app --host 0.0.0.0 --port=$PORT
    rootDir: backend

  - type: web
    name: chatbot-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    staticPublishPath: dist
    rootDir: frontend
